# Generated by Django 4.1.1 on 2023-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_type', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='media/images/logo_elim.png', null=True, upload_to='images', verbose_name='foto'),
        ),
    ]
