# Generated by Django 4.1.1 on 2023-05-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_type', '0005_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
