# Generated by Django 4.1.1 on 2023-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_type', '0007_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images', verbose_name='foto'),
        ),
    ]
